"""Add chat sessions and messages

Revision ID: e08cc2ed2902
Revises: bcf6ac2ab1bc
Create Date: 2026-04-11 22:51:27.704531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08cc2ed2902'
down_revision: Union[str, Sequence[str], None] = 'bcf6ac2ab1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # Add as nullable first to support existing documents, then backfill and enforce NOT NULL.
    op.add_column('documents', sa.Column('session_id', sa.String(), nullable=True))
    op.execute(
        sa.text(
            """
            INSERT INTO chat_sessions (id, title, created_at)
            SELECT 'legacy-session', 'Imported documents', NOW()
            WHERE EXISTS (SELECT 1 FROM documents)
            """
        )
    )
    op.execute(sa.text("UPDATE documents SET session_id = 'legacy-session' WHERE session_id IS NULL"))
    op.alter_column('documents', 'session_id', existing_type=sa.String(), nullable=False)
    op.create_foreign_key(
        'fk_documents_session_id_chat_sessions',
        'documents',
        'chat_sessions',
        ['session_id'],
        ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_session_id_chat_sessions', 'documents', type_='foreignkey')
    op.drop_column('documents', 'session_id')
    op.drop_table('chat_message')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
